export { createShopwareClient, type ShopwareClient } from './client'
export { ShopwareConnectionError } from './errors'
export { fetchShopInfo, toConnectionError, validateConnection } from './operations'
export { createSyncSink } from './sink'
export type { ShopInfo, ShopwareConnection } from './types'
