export { createShopwareClient, type ShopwareClient } from './client'
export { ShopwareConnectionError } from './errors'
export { fetchShopInfo, toConnectionError, validateConnection } from './operations'
export { ATOMIC_REQUEST_BYTE_LIMIT, createSyncSink, estimateSyncBytes } from './sink'
export type { ShopInfo, ShopwareConnection } from './types'
